### PR TITLE
separate subscriber and publisher

### PR DESCRIPTION
**Pull request by interBN**
**Issue:** https://github.com/sprinteins/oscd-plugins/issues/50

- [x] Instead of only **"Subscribers"** the sidebar makes a difference between **"Subscribers"** and **"Publishers"** in the title.

old:
image

new:
image

### CODE REVIEW

**Comment by interBN** [comment]
https://github.com/user-attachments/assets/d89f188a-fb2d-44c9-b775-80a5f091f4cf

**Review by LissiEitel — COMMENTED** [review]
For me it looks fine. 
I only asked myself, what happens if a item is publisher and subscriber? Can this happen?

**Comment by interBN** [comment]
> For me it looks fine. I only asked myself, what happens if a item is publisher and subscriber? Can this happen?

I am not 100% sure, but in this case the box will list the subscribers first and then the publishers.

[Please see](https://github.com/sprinteins/oscd-plugins/pull/106/files#diff-ffa334ec3eeca66f5c95b3be0d1a1a36633445c02aa0aa5e01db5e9e6358922aR73-R98)

**Review by LissiEitel — APPROVED** [review]
Approved from UX Side.

**Review by danyill — COMMENTED** [review]
Looks good to me, thanks for fixing this :+1:

**Pull request merged**
